"""Emit a provenance manifest for the ADL reproduction.

Captures everything a third party needs to check that this run happened, on this
code, in this environment: upstream commit, local diff vs upstream, resolved Hydra
configs, package versions, hardware, and sha256 of every result tensor.

Usage (on the pod): make_manifest.py <repo_dir> <results_root> <out_json>
"""
import hashlib
import json
import os
import platform
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(sys.argv[1])
RESULTS = Path(sys.argv[2])
OUT = Path(sys.argv[3])


def sh(cmd, cwd=None):
    try:
        return subprocess.run(
            cmd, shell=True, cwd=cwd, capture_output=True, text=True, timeout=180
        ).stdout.strip()
    except Exception as e:  # noqa: BLE001
        return f"<error: {e}>"


def sha256(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


manifest = {
    "generated_utc": datetime.now(timezone.utc).isoformat(),
    "purpose": (
        "Reproduction of the Activation Difference Lens (Minder et al., arXiv:2510.13900) "
        "on the subliminal_learning_cat organism (Qwen2.5-7B-Instruct + LoRA student "
        "trained on cat-teacher number sequences, Cloud et al. arXiv:2507.14805)."
    ),
    "upstream": {
        "repo": "https://github.com/science-of-finetuning/diffing-toolkit",
        "commit": sh("git rev-parse HEAD", cwd=REPO),
        "commit_subject": sh("git log -1 --pretty=%s", cwd=REPO),
        "commit_date": sh("git log -1 --pretty=%cI", cwd=REPO),
        "status_porcelain": sh("git status --porcelain", cwd=REPO),
        # The only substantive local change is the cu128 dependency constraint in
        # pyproject.toml. uv.lock is a machine-regenerated consequence of it, so its
        # full diff (~430k chars) is summarised rather than inlined; the originals are
        # preserved on disk as *.upstream-orig.
        "local_diff_stat": sh("git diff --stat", cwd=REPO),
        "local_diff_pyproject": sh("git diff -- pyproject.toml", cwd=REPO),
        "uv_lock_diff_note": (
            "uv.lock is regenerated by `uv lock` as a consequence of the pyproject "
            "constraint; diff omitted for size. Upstream copy kept at uv.lock.upstream-orig."
        ),
    },
    "organism": {
        "config": (REPO / "configs/organism/subliminal_learning_cat.yaml").read_text(),
        "base_model_config": (REPO / "configs/model/qwen25_7B_Instruct.yaml").read_text(),
    },
    "hardware": {
        "gpu": sh("nvidia-smi --query-gpu=name,memory.total,driver_version --format=csv,noheader"),
        "cuda_driver_version": sh("nvidia-smi --query-gpu=driver_version --format=csv,noheader"),
        "platform": platform.platform(),
        "python": sys.version,
        "cpu_count": os.cpu_count(),
    },
    "packages": {},
    "results": {},
}

# Key package versions, read from the venv actually used
pkg_probe = sh(
    "/opt/venv/bin/python -c \""
    "import torch,transformers,peft,nnsight,datasets;"
    "import importlib.metadata as m;"
    "print(torch.__version__);print(torch.version.cuda);print(transformers.__version__);"
    "print(peft.__version__);print(nnsight.__version__);print(datasets.__version__);"
    "print(m.version('vllm'));print(m.version('nnterp'))\""
)
keys = ["torch", "torch_cuda", "transformers", "peft", "nnsight", "datasets", "vllm", "nnterp"]
manifest["packages"] = dict(zip(keys, pkg_probe.splitlines()))
manifest["packages"]["full_freeze"] = sh("/opt/venv/bin/python -m pip freeze").splitlines()

# Resolved Hydra configs actually used by each run.
# infrastructure.storage.base_dir/hydra/<date>/<time>/.hydra/, i.e. a sibling of
# diffing_results — walk up until we find it rather than guessing a fixed depth.
hydra_root = None
for anc in [RESULTS] + list(RESULTS.parents):
    cand = anc / "hydra"
    if cand.is_dir():
        hydra_root = cand
        break
runs = []
if hydra_root is not None:
    for cfgp in sorted(hydra_root.glob("*/*/.hydra/config.yaml")):
        overrides = cfgp.parent / "overrides.yaml"
        runs.append(
            {
                "run_dir": str(cfgp.parent.parent),
                "overrides": overrides.read_text() if overrides.exists() else None,
                "resolved_config": cfgp.read_text(),
            }
        )
manifest["hydra_runs"] = runs

# sha256 of every result artifact
files = []
if RESULTS.exists():
    for p in sorted(RESULTS.rglob("*")):
        if p.is_file():
            files.append(
                {
                    "path": str(p.relative_to(RESULTS)),
                    "bytes": p.stat().st_size,
                    "sha256": sha256(p),
                }
            )
manifest["results"] = {"root": str(RESULTS), "file_count": len(files), "files": files}

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(json.dumps(manifest, indent=2))

# Flat checksum file too, for `sha256sum -c`
sums = OUT.parent / "sha256sums.txt"
sums.write_text("".join(f"{f['sha256']}  {f['path']}\n" for f in files))

print(f"manifest: {OUT}  ({len(files)} result files hashed)")
print("upstream commit:", manifest["upstream"]["commit"])
print("packages:", {k: v for k, v in manifest["packages"].items() if k != "full_freeze"})
print("hydra runs captured:", len(runs))
